### PR TITLE
feat: add ens name and avatar support

### PR DESCRIPTION
**Pull request by bigint**
Screenshot 2022-03-04 at 9 36 56 AM

cc @donosonaumczuk

### CODE REVIEW

**Review by donosonaumczuk — COMMENTED** [review]
Thanks @bigint for this contribution! As I said in the discord channel, let's wait for @defispartan review, he was working on ENS support at #280, I'm sure he would love to merge your avatar feature!

**Comment by defispartan** [comment]
Thanks for the contribution, this is a sweet addition! 

The package-lock.json changes are causing a ci error, but once that's fixed I think it's good to merge.

I think this is an issue of installing with an older npm version. If you update to npm version 7, then run `npm i` I think that should fix this issue :)

**Comment by defispartan** [comment]
Also I added you write access so you can create PRs directly on the repo now

**Comment by bigint** [comment]
@defispartan Thanks, this should be fixed now, and thanks for the access 🤗

**Review by defispartan — APPROVED** [review]
🚀

**Comment by jimmchang** [comment]
This is sick!!

**Pull request merged**
